name: CI/CD Pipeline

cd:
  name: Continuous Deployment
  needs: ci
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main'

  steps:
    - name: Deploy
      run: |
        echo "🚀 Deploying application..."
        echo "Add your deployment command here"
